// DO NOT EDIT — generated by _concept/03-orm-schema/codegen/diagram-to-drizzle.ts from _concept/02-diagram/schema.nesycat.json.
// Edit the diagram, then run: npm run db:diagram

import { pgTable, uuid, text, jsonb, timestamp, boolean, pgPolicy } from 'drizzle-orm/pg-core'
import { sql } from 'drizzle-orm'
import { authenticatedRole, authUid } from 'drizzle-orm/supabase'

export const diagrams = pgTable(
  'diagrams',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    ownedBy: uuid('owned_by').notNull(),
    title: text('title').notNull(),
    data: jsonb('data').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    pgPolicy('diagrams_select_own', { for: 'select', to: authenticatedRole, using: sql`${t.ownedBy} = ${authUid}` }),
    pgPolicy('diagrams_insert_own', { for: 'insert', to: authenticatedRole, withCheck: sql`${t.ownedBy} = ${authUid}` }),
    pgPolicy('diagrams_update_own', { for: 'update', to: authenticatedRole, using: sql`${t.ownedBy} = ${authUid}`, withCheck: sql`${t.ownedBy} = ${authUid}` }),
    pgPolicy('diagrams_delete_own', { for: 'delete', to: authenticatedRole, using: sql`${t.ownedBy} = ${authUid}` }),
  ],
)

export type Diagram = typeof diagrams.$inferSelect
export type NewDiagram = typeof diagrams.$inferInsert

export const organizations = pgTable(
  'organizations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    name: text('name').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    pgPolicy('organizations_select_member', { for: 'select', to: authenticatedRole, using: sql`${t.id} in (select public.my_member_organizations())` }),
    pgPolicy('organizations_insert_auth', { for: 'insert', to: authenticatedRole, withCheck: sql`true` }),
    pgPolicy('organizations_update_owner', { for: 'update', to: authenticatedRole, using: sql`${t.id} in (select public.my_owner_organizations())`, withCheck: sql`${t.id} in (select public.my_owner_organizations())` }),
    pgPolicy('organizations_delete_owner', { for: 'delete', to: authenticatedRole, using: sql`${t.id} in (select public.my_owner_organizations())` }),
  ],
)

export type Organization = typeof organizations.$inferSelect
export type NewOrganization = typeof organizations.$inferInsert

export const memberships = pgTable(
  'memberships',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id').notNull(),
    organizationId: uuid('organization_id').notNull(),
    isOwner: boolean('is_owner').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    pgPolicy('memberships_select_self', { for: 'select', to: authenticatedRole, using: sql`${t.userId} = ${authUid}` }),
    pgPolicy('memberships_select_member', { for: 'select', to: authenticatedRole, using: sql`${t.organizationId} in (select public.my_member_organizations())` }),
    pgPolicy('memberships_insert_owner', { for: 'insert', to: authenticatedRole, withCheck: sql`${t.organizationId} in (select public.my_owner_organizations())` }),
    pgPolicy('memberships_insert_bootstrap', { for: 'insert', to: authenticatedRole, withCheck: sql`${t.userId} = ${authUid} and ${t.isOwner} = true and public.organization_has_no_members(${t.organizationId})` }),
    pgPolicy('memberships_update_owner', { for: 'update', to: authenticatedRole, using: sql`${t.organizationId} in (select public.my_owner_organizations())`, withCheck: sql`${t.organizationId} in (select public.my_owner_organizations())` }),
    pgPolicy('memberships_delete_owner', { for: 'delete', to: authenticatedRole, using: sql`${t.organizationId} in (select public.my_owner_organizations())` }),
  ],
)

export type Membership = typeof memberships.$inferSelect
export type NewMembership = typeof memberships.$inferInsert
