import fs from 'node:fs'
import { ENV_TEST_LOCAL } from './paths'
import { assertLocalHost } from './safety'

// Writes a Next.js-recognized `.env.test.local` at the REPO ROOT (not under
// _tests/e2e-authed — Next.js only looks in the project root). This is the
// mechanism, not the cookie injection, that actually guarantees the authed
// webServer never touches the remote Supabase project:
//
// Next.js's env loader order (node_modules/next/dist/docs/01-app/02-guides/
// environment-variables.md, "Environment Variable Load Order") is:
//   1. .env.$(NODE_ENV).local
//   2. .env.local            — SKIPPED ENTIRELY when NODE_ENV=test
//   3. .env.$(NODE_ENV)
//   4. .env
//
// playwright.config.ts's authed webServer runs `next dev` with NODE_ENV=test
// set, so step 2 — the repo's real `.env.local`, which points at the
// production Supabase project — is never even opened for that process. Step
// 1 (`.env.test.local`, written here) wins outright. This is a stronger
// guarantee than "we override the right variables": even a variable this
// script forgot to set falls through to `.env.test` / `.env` (neither of
// which exist / are committed here), never to the remote `.env.local`.
//
// Gitignored by the ROOT .gitignore's existing `.env*` pattern (unrelated to
// this ticket's write set) — this file is a generated runtime artifact, not
// a tracked source file, exactly like `.next/` or `playwright-report/`.
export function writeAuthedEnvFile(opts: { supabaseUrl: string; anonKey: string; dbUrl: string }): void {
  assertLocalHost(opts.supabaseUrl, 'env-file Supabase URL')
  assertLocalHost(opts.dbUrl, 'env-file DB URL')
  const contents = `# Generated by _tests/e2e-authed/scripts/setup.ts — DO NOT EDIT BY HAND,
# and do not commit (matches the root .gitignore's .env* pattern already).
# Only loaded because the authed webServer runs with NODE_ENV=test — see this
# file's own lib/env-file.ts header comment for exactly why that makes it
# safe against ever resolving to the real (remote) .env.local.

NEXT_PUBLIC_SUPABASE_URL=${opts.supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${opts.anonKey}
DATABASE_URL=${opts.dbUrl}
DIRECT_URL=${opts.dbUrl}
POSTGRES_URL=${opts.dbUrl}
`
  fs.writeFileSync(ENV_TEST_LOCAL, contents)
}
