import path from 'node:path'

// __dirname here is <repo>/_tests/e2e-authed/lib — three levels up is the
// repo root. Resolved once, here, so every other module/script in this lane
// agrees on the same absolute paths regardless of its own cwd (npm scripts,
// Playwright's globalSetup, and a bare `npx tsx` invocation from a
// developer's shell can all have different cwds).
export const REPO_ROOT = path.resolve(__dirname, '..', '..', '..')

// The Supabase CLI looks for `supabase/config.toml` relative to cwd; this
// repo's real config lives at _concept/04-data-schema (see root CLAUDE.md's
// "Tooling quirks" section) — every `supabase` CLI call in this lane must
// run with this as its cwd.
export const SUPABASE_DIR = path.join(REPO_ROOT, '_concept', '04-data-schema')

export const SQL_DIR = path.join(REPO_ROOT, 'prisma', 'sql')

// This lane's own directory, for building paths relative to it regardless
// of caller cwd.
export const E2E_AUTHED_DIR = path.join(REPO_ROOT, '_tests', 'e2e-authed')

// Everything generated by setup.ts / auth.setup.ts — gitignored via this
// directory's own .gitignore (see _tests/e2e-authed/.gitignore).
export const GENERATED_DIR = path.join(E2E_AUTHED_DIR, '.generated')
export const STACK_JSON = path.join(GENERATED_DIR, 'stack.json')
export const AUTH_DIR = path.join(GENERATED_DIR, 'auth')
export const PRIMARY_STORAGE_STATE = path.join(AUTH_DIR, 'primary.json')
export const INVITEE_STORAGE_STATE = path.join(AUTH_DIR, 'invitee.json')

// Consumed by Next.js's own env loader (NOT hand-parsed by us) — see
// lib/env-file.ts's header comment for why this is safe against ever
// resolving to the real (remote) .env.local.
export const ENV_TEST_LOCAL = path.join(REPO_ROOT, '.env.test.local')
